name: Deploy my Function

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest    
    name: Deploy
    environment: dev
    steps:
      - uses: actions/checkout@v3  

      - name: Install Requirements
        uses: ./.github/actions/setup-requirements

      - name: Deploy on Prod
        uses: ./.github/actions/deployment

  deploy-staging:
    runs-on: ubuntu-latest    
    name: Deploy
    environment: staging
    steps:
      - uses: actions/checkout@v3  

      - name: Install Requirements
        uses: ./.github/actions/setup-requirements

      - name: Deploy on Prod
        uses: ./.github/actions/deployment
  
  deploy-prod:
    runs-on: ubuntu-latest    
    name: Deploy
    environment: prod
    steps:
      - uses: actions/checkout@v3  

      - name: Install Requirements
        uses: ./.github/actions/setup-requirements

      - name: Deploy on Prod
        uses: ./.github/actions/deployment


  