name: Deploy my Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest    
    name: Deploy
    steps:
      - uses: actions/checkout@v3  
      - name: Install Requirements
        uses: ./github/actions/setup-requirements
      - name: Deploy on ...
        uses: ./github/actions/deployment